
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nba_teams'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'pg-dbt-workshop'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["cohorts/2023/week_7_project/nba_teams/models/"]
analysis-paths: ["cohorts/2023/week_7_project/nba_teams/analysis/"]
test-paths: ["cohorts/2023/week_7_project/nba_teams/tests/"]
seed-paths: ["cohorts/2023/week_7_project/nba_teams/seeds/"]
macro-paths: ["cohorts/2023/week_7_project/nba_teams/macros/"]
snapshot-paths: ["cohorts/2023/week_7_project/nba_teams/snapshots/"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  nba_teams:
      # Applies to all files under models/.../
      staging:
          materialized: view
      core:
          materialized: table
# vars:
#   BMI: [1, 2, 3, 4, 5, 6]

# seeds: 
#     taxi_rides_ny:
#         taxi_zone_lookup:
#             +column_types:
#                 locationid: numeric
